#!/usr/bin/env python3

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

REQUIRED_PHRASES = {
    "docs/PLAYABLE_WORLD_TARGET.md": (
        "first-person player with crosshair",
        "flat terrain baseline",
        "mountain/8 by 8 multi-chunk generation mode",
        "digging and placing",
        "textured terrain material path",
        "future game-world addon name is undecided",
        "GDScript limited to scene scaffolding",
        "Map scale vocabulary",
        "2000×2000",
        "2000 blocks by 2000 blocks",
        "1 block = 1 meter",
        "4,000,000 m²",
        "4 km²",
        "93 active sparse path resources",
        "single-viewer playable streaming with a 25-resource active window",
        "dense generated 16 by 16 fixture with 256 generated pages",
        "32 by 32 fixture with 1024 generated pages",
        "generated fixture vertical coverage guard",
        "64 by 64 fixture with 4096 generated pages",
        "G15 locks G14 scale telemetry",
        "source sizes, source revision, vertical margins, engine markers, and active-resource budget",
        "128 by 128 dense generated near-2K playable streaming gate",
        "roughly a 2048 by 2048 block generated terrain step",
        "16384 generated pages",
        "G17 prepares the G16 near-2K generated project for human visual playtesting",
        "human_confirmation",
        "G18 is the production budget pivot",
        "no normal game path may require raw dense source files",
        "100 MiB hard per-file ceiling",
        "50 MiB target per-file ceiling",
        "30 seconds load-to-play ceiling",
        "G16 and G17 are stress-only evidence, not production terrain architecture",
        "G19 implements the first compact near-2K on-demand path",
        "deterministic procedural descriptor",
        "no `world.wtworld`",
        "100 MiB total budget",
        "G20 closes the compact terrain storage/load-shape issue",
        "dense near-2K source/world-file problem is resolved",
        "explicit 30 second timing evidence",
        "G21 prepares the compact G19 project for human visual playtesting",
        "human_confirmation as pending",
        "G22 runs the exact compact G21 handoff project",
        "automated PNG evidence",
        "carve and construct/place",
        "G23 fixes the failed human handoff",
        "player-driven streaming",
        "real input path",
        "G24 is reclassified as capped active-window regression evidence",
        "G25 replaces G24 as the active large-terrain visibility gate",
        "full 2048 by 2048 terrain visual coverage",
        "active window is only the local native Transvoxel detail layer",
        "G26 is the active first-person full-terrain playable-experience gate",
        "player-driven viewer updates remain active",
        "G27 is the active full-terrain human handoff preflight gate",
        "normal generated playtest scene",
        "event-driven material application",
        "bounded material-repair audit",
        "G28 is the active normal project launch preflight gate",
        "normal generated project launch",
        "automation safe by disabling human input",
        "restored to human input enabled",
        "G29 is the active compact 2K human-ready handoff gate",
        "human-ready compact 2K handoff project",
        "HUMAN_REVIEW.md",
        "G30 is the active compact 2K review bundle gate",
        "Compact 2K review bundle",
        "HANDOFF_MANIFEST.json",
        "G31 is the active review bundle launch preflight gate",
        "copied-bundle launch readiness",
        "bundle_launch_copy",
        "G32 is the active exact review-bundle autonomous runtime proof gate",
        "copied review-bundle runtime proof",
        "G33 is the active runtime terrain quality gate",
        "quality gates are the active direction",
        "Active track guardrails",
        "Post-G33 milestones must not be review, handoff, package, bundle, launch, or human-review milestones",
        "G34 is the active edit latency and persistence quality gate",
        "G35 is the active terrain correctness and artifact detection quality gate",
        "G36 is the active cold-idle performance quality gate",
        "G37 is the active streaming movement performance quality gate",
        "G38 is the active streaming endurance stability quality gate",
        "G39 is the active distributed edit streaming quality gate",
        "G40 is the active edit visual material feedback quality gate",
        "production world/terrain gap audit",
        "finite production roadmap",
        "Terrain 1.0",
        "G41 through G60",
        "automated validation-grade compact 2K terrain runtime",
        "runtime frame budget telemetry quality",
        "2048 by 2048",
        "not final terrain art",
    ),
    "docs/ROADMAP.md": (
        "## G2 - First-person playable baseline",
        "## G3 - Terrain generation modes",
        "## G4 - Terrain edit interaction",
        "## G5 - Material and performance baseline",
        "## G6 - Profile-selectable playable world",
        "## G7 - Human visual verification",
        "## G8 - 2000×2000 bounded streaming",
        "## G9 - Sparse 2K playable profile",
        "## G10 - Single-viewer 2K playable streaming",
        "## G11 - Generated 16x16 playable streaming",
        "## G12 - Generated 32x32 playable streaming",
        "## G13 - Generated fixture vertical coverage guard",
        "## G14 - Generated 64x64 playable streaming",
        "## G15 - G14 scale telemetry guard",
        "## G16 - Generated 128x128 playable streaming",
        "## G17 - Generated 128x128 human visual handoff",
        "## G18 - Production terrain budget pivot",
        "## G19 - Compact 2K on-demand procedural streaming",
        "## G20 - Compact terrain resolution gate",
        "## G21 - Compact 2K human visual handoff",
        "## G22 - Exact compact handoff runtime proof",
        "## G23 - Real compact human-playable streaming",
        "## G24 - Autonomous large-terrain acceptance",
        "## G25 - Full terrain visual baseline",
        "## G26 - Full terrain playable experience",
        "## G27 - Full terrain handoff preflight",
        "## G28 - Normal project launch preflight",
        "## G29 - Compact 2K human-ready handoff",
        "## G30 - Compact 2K review bundle",
        "## G31 - Review bundle launch preflight",
        "## G32 - Review bundle runtime proof",
        "## G33 - Runtime terrain quality gate",
        "## G34 - Edit latency persistence quality",
        "## G35 - Terrain correctness artifact quality",
        "## G36 - Cold idle performance quality",
        "## G37 - Streaming movement performance quality",
        "## G38 - Streaming endurance stability quality",
        "## G39 - Distributed edit streaming quality",
        "## G40 - Edit visual material feedback quality",
    ),
    "README.md": (
        "docs/PLAYABLE_WORLD_TARGET.md",
        "G7 human visual verification handoff is reproducible",
        "final human profile review remains pending",
        "python tools/validate_playable_world_target.py",
        "WT_VALIDATION_PLAYABLE_WORLD_TARGET_PASS",
        "G25 replaces G24 as the active large-terrain visibility gate",
        "G26 is the active first-person full-terrain playable-experience gate",
        "G27 is the active full-terrain human handoff preflight gate",
        "G28 is the active normal project launch preflight gate",
        "G29 is the active compact 2K human-ready handoff gate",
        "G30 is the active compact 2K review bundle gate",
        "G31 is the active review bundle launch preflight gate",
        "G32 is the active exact review-bundle autonomous runtime proof gate",
        "G33 is the active runtime terrain quality gate",
        "G34 is the active edit latency and persistence quality gate",
        "G35 is the active terrain correctness and artifact detection quality gate",
        "G36 is the active cold-idle performance quality gate",
        "G37 is the active streaming movement performance quality gate",
        "G38 is the active streaming endurance stability quality gate",
        "G39 is the active distributed edit streaming quality gate",
        "G40 is the active edit visual material feedback quality gate",
        "docs/PRODUCTION_WORLD_TERRAIN_GAP_AUDIT.md",
        "docs/FINITE_PRODUCTION_ROADMAP.md",
        "Terrain 1.0",
        "G41 through G60",
        "automated validation-grade compact 2K terrain runtime",
        "WT_VALIDATION_ACTIVE_TRACK_GUARDRAILS_PASS",
    ),
    "docs/PRODUCTION_WORLD_TERRAIN_GAP_AUDIT.md": (
        "automated validation-grade compact 2K terrain runtime, not production-ready large-world terrain",
        "Expected final world/terrain target",
        "Not production-ready yet",
        "Gap closure ladder",
        "runtime frame budget telemetry quality",
    ),
    "docs/FINITE_PRODUCTION_ROADMAP.md": (
        "Status: active roadmap contract",
        "Terrain 1.0 finish line",
        "Remaining Terrain 1.0 gates",
        "G41 - Runtime frame budget telemetry quality",
        "G60 - Terrain 1.0 release candidate quality",
    ),
}


def main() -> None:
    errors: list[str] = []
    for relative, phrases in REQUIRED_PHRASES.items():
        path = ROOT / relative
        if not path.is_file():
            errors.append(f"missing playable-world file: {relative}")
            continue
        text = path.read_text(encoding="utf-8")
        normalized = " ".join(text.split())
        for phrase in phrases:
            if phrase not in text and phrase not in normalized:
                errors.append(f"{relative} missing phrase: {phrase}")
    for error in errors:
        print(f"ERROR: {error}")
    if errors:
        raise SystemExit(1)
    print("WT_VALIDATION_PLAYABLE_WORLD_TARGET_PASS next=runtime_frame_budget_telemetry_quality")


if __name__ == "__main__":
    main()
